---
swagger: '2.0'
info:
  title: Spotify Web API
  description: |
    Welcome to the _Spotify Web API_ specification. For more information about
    how to use the API, check out [Spotify's developer site](https://developer.spotify.com/web-api/).
  version: v1
host: api.spotify.com
x-basePath: "/{version}"
schemes:
  - https
securityDefinitions:
  oauth_2_0:
    description: 'Spotify supports OAuth 2.0 for authenticating all API requests.'
    type: oauth2
    flow: accessCode
    authorizationUrl: https://accounts.spotify.com/authorize
    tokenUrl: https://accounts.spotify.com/api/token
    scopes:
      playlist-read-private: ''
      playlist-read-collaborative: ''
      playlist-modify-public: ''
      playlist-modify-private: ''
      user-library-read: ''
      user-library-modify: ''
      user-read-private: ''
      user-read-birthdate: ''
      user-read-email: ''
      user-follow-read: ''
      user-follow-modify: ''
      user-top-read: ''
paths:
  "/albums":
    get:
      description: "[Get Several Albums](https://developer.spotify.com/web-api/get-several-albums/)\n"
      operationId: GET_albums
      security:
        - oauth_2_0: []
  "/albums/{id}":
    get:
      description: "[Get an Album](https://developer.spotify.com/web-api/get-album/)\n"
      operationId: GET_albums-id
      security:
        - oauth_2_0: []
  "/albums/{id}/tracks":
    get:
      description: "[Get an Album's Tracks](https://developer.spotify.com/web-api/get-albums-tracks/)\n"
      operationId: GET_albums-id-tracks
      security:
        - oauth_2_0: []
  "/artists":
    get:
      description: "[Get Several Artists](https://developer.spotify.com/web-api/get-several-artists/)\n"
      operationId: GET_artists
      security:
        - oauth_2_0: []
  "/artists/{id}":
    get:
      description: "[Get an Artist](https://developer.spotify.com/web-api/get-artist/)\n"
      operationId: GET_artists-id
      security:
        - oauth_2_0: []
  "/artists/{id}/top-tracks":
    get:
      description: "[Get an Artist's Top Tracks](https://developer.spotify.com/web-api/get-artists-top-tracks/)\n"
      operationId: GET_artists-id-top-tracks
      security:
        - oauth_2_0: []
  "/artists/{id}/related-artists":
    get:
      description: "[Get an Artist's Related Artists](https://developer.spotify.com/web-api/get-related-artists/)\n"
      operationId: GET_artists-id-related-artists
      security:
        - oauth_2_0: []
  "/artists/{id}/albums":
    get:
      description: "[Get an Artist's Albums](https://developer.spotify.com/web-api/get-artists-albums/)\n"
      operationId: GET_artists-id-albums
      security:
        - oauth_2_0: []
  "/tracks":
    get:
      description: "[Get Several Tracks](https://developer.spotify.com/web-api/get-several-tracks/)\n"
      operationId: GET_tracks
      security:
        - oauth_2_0: []
  "/tracks/{id}":
    get:
      description: "[Get a Track](https://developer.spotify.com/web-api/get-track/)\n"
      operationId: GET_tracks-id
      security:
        - oauth_2_0: []
  "/search":
    get:
      description: "[Search for an Item](https://developer.spotify.com/web-api/search-item/)\n"
      operationId: GET_search
      security:
        - oauth_2_0: []
  "/me":
    get:
      description: "[Get Current User's Profile](https://developer.spotify.com/web-api/get-current-users-profile/)\n"
      operationId: GET_me
  "/me/playlists":
    get:
      description: "[Get a List of Current User's Playlists](https://developer.spotify.com/web-api/get-a-list-of-current-users-playlists/)\n"
      operationId: GET_me-playlists
      security:
        - oauth_2_0:
            - playlist-read-private
        - oauth_2_0:
            - user-read-private
            - user-read-birthdate
            - user-read-email
  "/me/albums":
    get:
      description: "[Get Current User's Saved Albums](https://developer.spotify.com/web-api/get-users-saved-albums/)\n"
      operationId: GET_me-albums
      security:
        - oauth_2_0:
            - user-library-read
        - oauth_2_0:
            - user-read-private
            - user-read-birthdate
            - user-read-email
    put:
      description: "[Save Albums for Current User](https://developer.spotify.com/web-api/save-albums-user/)\n"
      operationId: PUT_me-albums
      security:
        - oauth_2_0:
            - user-library-modify
        - oauth_2_0:
            - user-read-private
            - user-read-birthdate
            - user-read-email
    delete:
      description: "[Remove Albums for Current User](https://developer.spotify.com/web-api/remove-albums-user/)\n"
      operationId: DELETE_me-albums
      security:
        - oauth_2_0:
            - user-library-modify
        - oauth_2_0:
            - user-read-private
            - user-read-birthdate
            - user-read-email
  "/me/albums/contains":
    get:
      description: "[Check Current User's Saved Albums](https://developer.spotify.com/web-api/check-users-saved-albums/)\n"
      operationId: GET_me-albums-contains
      security:
        - oauth_2_0:
            - user-library-read
        - oauth_2_0:
            - user-read-private
            - user-read-birthdate
            - user-read-email
  "/me/tracks":
    get:
      description: "[Get Current User's Saved Tracks](https://developer.spotify.com/web-api/get-users-saved-tracks/)\n"
      operationId: GET_me-tracks
      security:
        - oauth_2_0:
            - user-library-read
        - oauth_2_0:
            - user-read-private
            - user-read-birthdate
            - user-read-email
    put:
      description: "[Save Tracks for Current User](https://developer.spotify.com/web-api/save-tracks-user/)\n"
      operationId: PUT_me-tracks
      security:
        - oauth_2_0:
            - user-library-modify
        - oauth_2_0:
            - user-read-private
            - user-read-birthdate
            - user-read-email
    delete:
      description: "[Remove Tracks for Current User](https://developer.spotify.com/web-api/remove-tracks-user/)\n"
      operationId: DELETE_me-tracks
      security:
        - oauth_2_0:
            - user-library-modify
        - oauth_2_0:
            - user-read-private
            - user-read-birthdate
            - user-read-email
  "/me/tracks/contains":
    get:
      description: "[Check Current User's Saved Tracks](https://developer.spotify.com/web-api/check-users-saved-tracks/)\n"
      operationId: GET_me-tracks-contains
      security:
        - oauth_2_0:
            - user-library-read
        - oauth_2_0:
            - user-read-private
            - user-read-birthdate
            - user-read-email
  "/me/top/{type}":
    get:
      description: "[Get User's Top Artists and Tracks](https://developer.spotify.com/web-api/get-users-top-artists-and-tracks/)\n"
      operationId: GET_me-top-type
      security:
        - oauth_2_0:
            - user-top-read
        - oauth_2_0:
            - user-read-private
            - user-read-birthdate
            - user-read-email
  "/users/{user_id}":
    get:
      description: "[Get a User's Profile](https://developer.spotify.com/web-api/get-users-profile/)\n"
      operationId: GET_users-user_id
      security:
        - oauth_2_0: []
  "/users/{user_id}/playlists":
    get:
      description: "[Get a List of a User's Playlists](https://developer.spotify.com/web-api/get-list-users-playlists/)\n"
      operationId: GET_users-user_id-playlists
      security:
        - oauth_2_0:
            - playlist-read-private
            - playlist-read-collaborative
    post:
      description: "[Create a Playlist](https://developer.spotify.com/web-api/create-playlist/)\n"
      operationId: POST_users-user_id-playlists
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
  "/users/{user_id}/playlists/{playlist_id}":
    get:
      description: "[Get a Playlist](https://developer.spotify.com/web-api/get-playlist/)\n"
      operationId: GET_users-user_id-playlists-playlist_id
      security:
        - oauth_2_0: []
    put:
      description: "[Change a Playlist's Details](https://developer.spotify.com/web-api/change-playlist-details/)\n"
      operationId: PUT_users-user_id-playlists-playlist_id
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
  "/users/{user_id}/playlists/{playlist_id}/tracks":
    get:
      description: "[Get a Playlist's Tracks](https://developer.spotify.com/web-api/get-playlists-tracks/)\n"
      operationId: GET_users-user_id-playlists-playlist_id-tracks
      security:
        - oauth_2_0: []
    post:
      description: "[Add Tracks to a Playlist](https://developer.spotify.com/web-api/add-tracks-to-playlist/)\n"
      operationId: POST_users-user_id-playlists-playlist_id-tracks
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
    put:
      description: "[Reorder or replace a Playlist's Tracks](https://developer.spotify.com/web-api/reorder-playlists-tracks/)\n"
      operationId: PUT_users-user_id-playlists-playlist_id-tracks
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
    delete:
      description: "[Remove Tracks from a Playlist](https://developer.spotify.com/web-api/remove-tracks-playlist/)\n"
      operationId: DELETE_users-user_id-playlists-playlist_id-tracks
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
  "/users/{user_id}/playlists/{playlist_id}/followers":
    put:
      description: "[Follow a Playlist](https://developer.spotify.com/web-api/follow-playlist/)\n"
      operationId: PUT_users-user_id-playlists-playlist_id-followers
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
    delete:
      description: "[Unfollow a Playlist](https://developer.spotify.com/web-api/unfollow-playlist/)\n"
      operationId: DELETE_users-user_id-playlists-playlist_id-followers
      security:
        - oauth_2_0:
            - playlist-modify-public
            - playlist-modify-private
  "/users/{user_id}/playlists/{playlist_id}/followers/contains":
    get:
      description: "[Check if Users Follow a Playlist](https://developer.spotify.com/web-api/check-user-following-playlist/)\n"
      operationId: GET_users-user_id-playlists-playlist_id-followers-contains
      security:
        - oauth_2_0: []
  "/browse/new-releases":
    get:
      description: "[Get a List of New Releases](https://developer.spotify.com/web-api/get-list-new-releases/)\n"
      operationId: GET_browse-new-releases
      security:
        - oauth_2_0: []
  "/browse/featured-playlists":
    get:
      description: "[Get a List of Featured Playlists](https://developer.spotify.com/web-api/get-list-featured-playlists/)\n"
      operationId: GET_browse-featured-playlists
      security:
        - oauth_2_0: []
  "/browse/categories":
    get:
      description: "[Get a List of Browse Categories](https://developer.spotify.com/web-api/get-list-categories/)\n"
      operationId: GET_browse-categories
      security:
        - oauth_2_0: []
  "/browse/categories/{category_id}":
    get:
      description: "[Get a Single Browse Category](https://developer.spotify.com/web-api/get-category/)\n"
      operationId: GET_browse-categories-category_id
      security:
        - oauth_2_0: []
  "/browse/categories/{category_id}/playlists":
    get:
      description: "[Get a Category's playlists](https://developer.spotify.com/web-api/get-categorys-playlists/)\n"
      operationId: GET_browse-categories-category_id-playlists
      security:
        - oauth_2_0: []
  "/me/following":
    get:
      description: "[Get User's Followed Artists](https://developer.spotify.com/web-api/get-followed/)\n"
      operationId: GET_me-following
      security:
        - oauth_2_0:
            - user-follow-read
    put:
      description: "[Follow Artists or Users](https://developer.spotify.com/web-api/follow-artists-users/)\n"
      operationId: PUT_me-following
      security:
        - oauth_2_0:
            - user-follow-modify
    delete:
      description: "[Unfollow Artists or Users](https://developer.spotify.com/web-api/unfollow-artists-users/)\n"
      operationId: DELETE_me-following
      security:
        - oauth_2_0:
            - user-follow-modify
  "/me/following/contains":
    get:
      description: "[Check if Current User Follows Artists or Users](https://developer.spotify.com/web-api/check-current-user-follows/)\n"
      operationId: GET_me-following-contains
      security:
        - oauth_2_0:
            - user-follow-read
  "/audio-features":
    get:
      description: "[Get Audio Features for Several Tracks](https://developer.spotify.com/web-api/get-several-audio-features/)\n"
      operationId: GET_audio-features
      security:
        - oauth_2_0: []
  "/audio-features/{id}":
    get:
      description: "[Get Audio Features for a Track](https://developer.spotify.com/web-api/get-audio-features/)\n"
      operationId: GET_audio-features-id
      security:
        - oauth_2_0: []
  "/audio-analysis/{id}":
    get:
      description: "[Get Audio Analysis for a Track](https://developer.spotify.com/web-api/get-audio-analysis/)\n"
      operationId: GET_audio-analysis-id
      security:
        - oauth_2_0: []
  "/recommendations":
    get:
      description: "[Get Recommendations Based on Seeds](https://developer.spotify.com/web-api/get-recommendations/)\n"
      operationId: GET_recommendations
      security:
        - oauth_2_0: []
  "/recommendations/available-genre-seeds":
    get:
      description: "[Get Available Genre Seeds](https://developer.spotify.com/web-api/get-recommendations/#available-genre-seeds)\n"
      operationId: GET_recommendations-available-genre-seeds
      security:
        - oauth_2_0: []
