// tslint:disable
/**
 * Spotify Web API
 * Welcome to the _Spotify Web API_ specification. For more information about how to use the API, check out [Spotify\'s developer site](https://developer.spotify.com/web-api/). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Image,
} from './';

/**
 * @export
 * @interface AlbumSimple
 */
export interface AlbumSimple {
    /**
     * The type of the album: one of \'album\', \'single\', or \'compilation\'.
     * @type {string}
     * @memberof AlbumSimple
     */
    album_type?: string;
    /**
     * The markets in which the album is available: ISO 3166-1 alpha-2 country codes. Note that an album is considered available in a market when at least 1 of its tracks is available in that market.
     * @type {Array<string>}
     * @memberof AlbumSimple
     */
    available_markets?: Array<string>;
    /**
     * Known external URLs for this album.
     * @type {{ [key: string]: string; }}
     * @memberof AlbumSimple
     */
    external_urls?: { [key: string]: string; };
    /**
     * A link to the Web API endpoint providing full details of the album.
     * @type {string}
     * @memberof AlbumSimple
     */
    href?: string;
    /**
     * The Spotify ID for the album.
     * @type {string}
     * @memberof AlbumSimple
     */
    id?: string;
    /**
     * The cover art for the album in various sizes, widest first.
     * @type {Array<Image>}
     * @memberof AlbumSimple
     */
    images?: Array<Image>;
    /**
     * The name of the album.
     * @type {string}
     * @memberof AlbumSimple
     */
    name?: string;
    /**
     * The object type: \'album\'.
     * @type {string}
     * @memberof AlbumSimple
     */
    type?: string;
    /**
     * The Spotify URI for the album.
     * @type {string}
     * @memberof AlbumSimple
     */
    uri?: string;
}
