// tslint:disable
/**
 * Spotify Web API
 * Welcome to the _Spotify Web API_ specification. For more information about how to use the API, check out [Spotify\'s developer site](https://developer.spotify.com/web-api/). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AlbumCopyrights
 */
export interface AlbumCopyrights {
    /**
     * The copyright text for this album.
     * @type {string}
     * @memberof AlbumCopyrights
     */
    text?: string;
    /**
     * The type of copyright: C = the copyright, P = the sound recording (performance) copyright.
     * @type {string}
     * @memberof AlbumCopyrights
     */
    type?: string;
}
