// tslint:disable
/**
 * Spotify Web API
 * Welcome to the _Spotify Web API_ specification. For more information about how to use the API, check out [Spotify\'s developer site](https://developer.spotify.com/web-api/). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ArtistSimple
 */
export interface ArtistSimple {
    /**
     * Known external URLs for this artist.
     * @type {{ [key: string]: string; }}
     * @memberof ArtistSimple
     */
    external_urls?: { [key: string]: string; };
    /**
     * A link to the Web API endpoint providing full details of the artist.
     * @type {string}
     * @memberof ArtistSimple
     */
    href?: string;
    /**
     * The Spotify ID for the artist.
     * @type {string}
     * @memberof ArtistSimple
     */
    id?: string;
    /**
     * The name of the artist.
     * @type {string}
     * @memberof ArtistSimple
     */
    name?: string;
    /**
     * The object type: \'artist\'
     * @type {string}
     * @memberof ArtistSimple
     */
    type?: string;
    /**
     * The Spotify URI for the artist.
     * @type {string}
     * @memberof ArtistSimple
     */
    uri?: string;
}
