// tslint:disable
/**
 * Spotify Web API
 * Welcome to the _Spotify Web API_ specification. For more information about how to use the API, check out [Spotify\'s developer site](https://developer.spotify.com/web-api/). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * The image height in pixels. If unknown: null or not returned.
     * @type {number}
     * @memberof Image
     */
    height?: number;
    /**
     * The source URL of the image.
     * @type {string}
     * @memberof Image
     */
    url?: string;
    /**
     * The image width in pixels. If unknown: null or not returned.
     * @type {number}
     * @memberof Image
     */
    width?: number;
}
