// tslint:disable
/**
 * Spotify Web API
 * Welcome to the _Spotify Web API_ specification. For more information about how to use the API, check out [Spotify\'s developer site](https://developer.spotify.com/web-api/). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Album,
} from './';

/**
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * @type {Array<Album>}
     * @memberof InlineResponse200
     */
    albums?: Array<Album>;
}
