// tslint:disable
/**
 * Spotify Web API
 * Welcome to the _Spotify Web API_ specification. For more information about how to use the API, check out [Spotify\'s developer site](https://developer.spotify.com/web-api/). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PlaylistSnapshot
 */
export interface PlaylistSnapshot {
    /**
     * The version identifier for the modified playlist. Can be supplied in other requests to target a specific playlist version.
     * @type {string}
     * @memberof PlaylistSnapshot
     */
    snapshot_id?: string;
}
