// tslint:disable
/**
 * Spotify Web API
 * Welcome to the _Spotify Web API_ specification. For more information about how to use the API, check out [Spotify\'s developer site](https://developer.spotify.com/web-api/). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PlaylistSimpleTracks
 */
export interface PlaylistSimpleTracks {
    /**
     * A link to the Web API endpoint returning the full result of the request.
     * @type {string}
     * @memberof PlaylistSimpleTracks
     */
    href?: string;
    /**
     * The total number of tracks available to return.
     * @type {number}
     * @memberof PlaylistSimpleTracks
     */
    total?: number;
}
