// tslint:disable
/**
 * Spotify Web API
 * Welcome to the _Spotify Web API_ specification. For more information about how to use the API, check out [Spotify\'s developer site](https://developer.spotify.com/web-api/). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Track,
    UserProfile,
} from './';

/**
 * @export
 * @interface PlaylistTrack
 */
export interface PlaylistTrack {
    /**
     * The date and time the track was added in ISO 8601 format. Note that some very old playlists may return null in this field.
     * @type {string}
     * @memberof PlaylistTrack
     */
    added_at?: string;
    /**
     * @type {UserProfile}
     * @memberof PlaylistTrack
     */
    added_by?: UserProfile;
    /**
     * Whether this track is a [local file](https://developer.spotify.com/web-api/local-files-spotify-playlists/) or not.
     * @type {boolean}
     * @memberof PlaylistTrack
     */
    is_local?: boolean;
    /**
     * @type {Track}
     * @memberof PlaylistTrack
     */
    track?: Track;
}
