// tslint:disable
/**
 * Spotify Web API
 * Welcome to the _Spotify Web API_ specification. For more information about how to use the API, check out [Spotify\'s developer site](https://developer.spotify.com/web-api/). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Track,
} from './';

/**
 * @export
 * @interface SavedTrack
 */
export interface SavedTrack {
    /**
     * The date and time the track was added in ISO 8601 format. Note that some very old playlists may return null in this field.
     * @type {string}
     * @memberof SavedTrack
     */
    added_at?: string;
    /**
     * @type {Track}
     * @memberof SavedTrack
     */
    track?: Track;
}
