// tslint:disable
/**
 * Spotify Web API
 * Welcome to the _Spotify Web API_ specification. For more information about how to use the API, check out [Spotify\'s developer site](https://developer.spotify.com/web-api/). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ArtistSimple,
    TrackLinkedFrom,
} from './';

/**
 * @export
 * @interface TrackSimple
 */
export interface TrackSimple {
    /**
     * The artists who performed the track. Each artist object includes a link in href to more detailed information about the artist.
     * @type {Array<ArtistSimple>}
     * @memberof TrackSimple
     */
    artists?: Array<ArtistSimple>;
    /**
     * A list of the countries in which the track can be played, identified by their ISO 3166-1 alpha-2 code. 
     * @type {Array<string>}
     * @memberof TrackSimple
     */
    available_markets?: Array<string>;
    /**
     * The disc number (usually 1 unless the album consists of more than one disc).
     * @type {number}
     * @memberof TrackSimple
     */
    disc_number?: number;
    /**
     * The track length in milliseconds.
     * @type {number}
     * @memberof TrackSimple
     */
    duration_ms?: number;
    /**
     * Whether or not the track has explicit lyrics (true = yes it does; false = no it does not OR unknown).
     * @type {boolean}
     * @memberof TrackSimple
     */
    explicit?: boolean;
    /**
     * Known external URLs for this track.
     * @type {{ [key: string]: string; }}
     * @memberof TrackSimple
     */
    external_urls?: { [key: string]: string; };
    /**
     * A link to the Web API endpoint providing full details of the track.
     * @type {string}
     * @memberof TrackSimple
     */
    href?: string;
    /**
     * The Spotify ID for the track.
     * @type {string}
     * @memberof TrackSimple
     */
    id?: string;
    /**
     * Part of the response when Track Relinking is applied. If true, the track is playable in the given market. Otherwise false.
     * @type {boolean}
     * @memberof TrackSimple
     */
    is_playable?: boolean;
    /**
     * @type {TrackLinkedFrom}
     * @memberof TrackSimple
     */
    linked_from?: TrackLinkedFrom;
    /**
     * The name of the track.
     * @type {string}
     * @memberof TrackSimple
     */
    name?: string;
    /**
     * A URL to a 30 second preview (MP3 format) of the track.
     * @type {string}
     * @memberof TrackSimple
     */
    preview_url?: string;
    /**
     * The number of the track. If an album has several discs, the track number is the number on the specified disc.
     * @type {number}
     * @memberof TrackSimple
     */
    track_number?: number;
    /**
     * The object type: \'track\'.
     * @type {string}
     * @memberof TrackSimple
     */
    type?: string;
    /**
     * The Spotify URI for the track.
     * @type {string}
     * @memberof TrackSimple
     */
    uri?: string;
}
