// tslint:disable
/**
 * Spotify Web API
 * Welcome to the _Spotify Web API_ specification. For more information about how to use the API, check out [Spotify\'s developer site](https://developer.spotify.com/web-api/). 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Followers,
} from './';

/**
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
    /**
     * The name displayed on the user\'s profile.
     * @type {string}
     * @memberof UserProfile
     */
    displayName?: string;
    /**
     * Known external URLs for this user.
     * @type {{ [key: string]: string; }}
     * @memberof UserProfile
     */
    external_urls?: { [key: string]: string; };
    /**
     * @type {Followers}
     * @memberof UserProfile
     */
    followers?: Followers;
    /**
     * A link to the Web API endpoint for this user.
     * @type {string}
     * @memberof UserProfile
     */
    href?: string;
    /**
     * The Spotify ID for this user.
     * @type {string}
     * @memberof UserProfile
     */
    id?: string;
    /**
     * The object type: \'user\'
     * @type {string}
     * @memberof UserProfile
     */
    type?: string;
    /**
     * The Spotify URI for the user.
     * @type {string}
     * @memberof UserProfile
     */
    uri?: string;
}
